# This workflow will build a Java project with Maven
# For more information see:
# - https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
# - https://github.com/actions/setup-java
# - https://github.com/actions/starter-workflows/edit/master/ci/maven.yml
# - https://github.com/actions/cache/blob/master/examples.md#java---maven

name: Maven test, build and verify

on:
  push:
    branches-ignore:
    - master
  pull_request:
    branches-ignore:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest update of each major Java version:
        java: [ 8, 9, 10, 11, 12, 13, 14 ]
    name: Build with Java ${{ matrix.java }}

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}

    - name: Cache Maven dependencies between builds
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-jdk${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-jdk${{ matrix.java }}-

    - name: Build and Verify with Maven on Java ${{ matrix.java }}
      run: mvn -B --show-version -Dmaven.skip.macSigning=true clean verify

    - name: Archive App & Jar build snapshots for Java 8
      uses: actions/upload-artifact@v2
      if: matrix.java == '8'
      with:
        name: App-Snapshots-Java-${{ matrix.java }}
        path: target/EPUB-Checker-*.zip
